# -*- coding: utf-8 -*-
"""ques7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H5aXYANzNtnmo7v-WEUSa1ipah5AUoDB
"""

import pandas as pd
data = pd.read_csv("diamonds.csv")
data.head()

