# -*- coding: utf-8 -*-
"""ques11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SYSRUDJjyVnf8oMMUQM8mpleE1lM5cXZ
"""

import pandas as pd
df = pd.read_csv("diamonds.csv")
print("count of duplicated rows is as follows")
print(df.duplicated().sum())

print("for checking purpose,") 
print(df.duplicated())

