# -*- coding: utf-8 -*-
"""ques3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1krOHM7O95pvk-8wGEVnXSwY3yVWl9MG5
"""

list1 =[1,2,3,4,5,6,7]
print("list1 : ",list1)
even = []
odd = []
for i in list1:
    if i%2 ==0:
        even.append(i)
    else:
        odd.append(i)
print("the even list is:", even)
print("the odd list is:",odd)

