# -*- coding: utf-8 -*-
"""ques8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nY9ZiGW8Zhhk8TTh_g_38BnoZeULlQRz
"""

import pandas as pd
data = pd.read_csv("diamonds.csv")
data.cut

