# -*- coding: utf-8 -*-
"""ques12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m0uNu0M4qoFgNOS99c_TkAHwl72Rr0_I
"""

import pandas as pd
df = pd.read_csv("diamonds.csv")

import numpy as np
a,b= df.shape
a = int(0.75*a)
dfs = np.split(df,[0,a],axis=0)

df1 = dfs[1]
df2 = dfs[2]
print("The dataframe df1, containing  first 75 percent of dataframe is as follows: \n",df1)
print("\n")
print("The dataframe df2, containing remaining 25 percent of dataframe is as follows \n",df2)

