# -*- coding: utf-8 -*-
"""ques4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCWnW_9mgH56JY23ySUV2kxdkT1YMK2v
"""

sample = {'physics':88, 'maths':75, 'chemistry':72, 'Basic electrical':89}
key_max = max(sample.keys(), key = (lambda k : sample[k] ))
key_min = min(sample.keys(), key = (lambda k : sample[k] ))
print ('Maximum Value:', sample[key_max])
print ('Minimum Value:', sample[key_min])

