# -*- coding: utf-8 -*-
"""ques10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vJSLW86RUwhMymKs6lL1Ot0Kg0KQsBJe
"""

import pandas as pd
df = pd.read_csv("diamonds.csv")
print("The shape of original dataframe is",df.shape)
print("The remaining shape excluding dataframe containing any mising values(if any) is",df.dropna(how='any').shape)
print("\n")
if df.shape == df.dropna(how='any').shape:
  print(" Hence there are no missing values \n Therefore,the dataframe remains unchanged")
  print("\n")
  print(df)
else:
  df.dropna(how="any")
  df

