# -*- coding: utf-8 -*-
"""ques2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w6_Y-EbX3GjwxQtp-0vO6yMlqb0mc5Hn
"""

str = 'MeMorIeS '
words = str.split()
lower = []
upper = []
for char in str:
    if char.islower():
        lower.append(char)
    else:
        upper.append(char)
newstring = ''.join(lower + upper)
print("arranging letters in required order :",newstring)

