# -*- coding: utf-8 -*-
"""ques5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QjRXa1WqyARfbk_5GpJkbnfQ3WDCtNkO
"""

s1 = {1,2,3,4,5,6,7,8,9}
s2 = {1,3,4,6,8,11,22,34,51,67}
s1.difference_update(s2)
print(s1, " is the new updated set")

